app:
  port: 1399

mongodb:
  conns: mongodb://omrdev:omrdev2014@andromeda11.tac.co.th:27017
  database: dev2

salt:
  spec:
    url: http://athena13.tac.co.th:9582/
    method: POST
    content-type: xml
    timeout: 3
    basic-auth:
      username: LLCRMWS
      password: dtac1234