app:
  port: 1399

mongodb:
  conns: mongodb://user:pass@mongodb:27017
  database: dev

salt:
  spec:
    url: http://seiya:9582/
    method: POST
    content-type: xml
    timeout: 3
    basic-auth:
      username: LLAAAAAAA
      password: DDDD1111
